name: master

on:
  push:
    branches: [master]

env:
  NODE_VERSION: 14
  FORCE_COLOR: 3

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get Yarn cache directory
        id: get-yarn-cache-dir
        run: echo "::set-output name=path::$(yarn cache dir)"
      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.get-yarn-cache-dir.outputs.path }}
          key: "${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-\
            ${{ hashFiles('**/yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: reggionick/s3-deploy@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          folder: build
          bucket: docs.tor.us
          dist-id: E11JKICTZIXMQH
          delete-removed: true
